// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUwgoZLsq8daDj2UGXKKowp6SvS6qNmC8',
    appId: '1:1039363994934:web:797d2596d19d488a646f97',
    messagingSenderId: '1039363994934',
    projectId: 'e-commerce-app-88ab6',
    authDomain: 'e-commerce-app-88ab6.firebaseapp.com',
    storageBucket: 'e-commerce-app-88ab6.firebasestorage.app',
    measurementId: 'G-GEW2Z6PM6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn8QAidCtEftazu1CsJypT4uYKpAs_kaQ',
    appId: '1:1039363994934:android:7032977512ef8e30646f97',
    messagingSenderId: '1039363994934',
    projectId: 'e-commerce-app-88ab6',
    storageBucket: 'e-commerce-app-88ab6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsWd6pchXMCJZdsCyxi-fMiRqSylqe6AA',
    appId: '1:1039363994934:ios:aa3685c1cae31d05646f97',
    messagingSenderId: '1039363994934',
    projectId: 'e-commerce-app-88ab6',
    storageBucket: 'e-commerce-app-88ab6.firebasestorage.app',
    androidClientId: '1039363994934-esqs6em9040b5c55v1ca4dqqobkqksjb.apps.googleusercontent.com',
    iosClientId: '1039363994934-s3os8s6tlf3eq71j04130c02iknitaut.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsWd6pchXMCJZdsCyxi-fMiRqSylqe6AA',
    appId: '1:1039363994934:ios:aa3685c1cae31d05646f97',
    messagingSenderId: '1039363994934',
    projectId: 'e-commerce-app-88ab6',
    storageBucket: 'e-commerce-app-88ab6.firebasestorage.app',
    androidClientId: '1039363994934-esqs6em9040b5c55v1ca4dqqobkqksjb.apps.googleusercontent.com',
    iosClientId: '1039363994934-s3os8s6tlf3eq71j04130c02iknitaut.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUwgoZLsq8daDj2UGXKKowp6SvS6qNmC8',
    appId: '1:1039363994934:web:2c61c6389494bcb9646f97',
    messagingSenderId: '1039363994934',
    projectId: 'e-commerce-app-88ab6',
    authDomain: 'e-commerce-app-88ab6.firebaseapp.com',
    storageBucket: 'e-commerce-app-88ab6.firebasestorage.app',
    measurementId: 'G-P58SWW4C6F',
  );
}
